// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { z } from 'zod'

import type { AssumptionRecord, Finding, Resolution } from '../agent-layer.js'
import { FindingsSidecarSchema } from '../agent-layer.js'
import type { DigestRecord } from '../legacy-fold.js'
import { formatDigestBody } from './digest-format.js'
import { listAgentArtifacts, recordArtifactHashes } from './gate-files.js'
import { ResolverOutputSchema } from './review-loop.js'
import { evaluateConvergence } from './review-model.js'
import type { ArtifactDigests } from './review-model.js'

const REVIEW_HEADER =
  '<!-- GENERATED by afk-runner from findings/resolutions sidecars - regenerated wholesale per round. -->'
const ASSUMPTIONS_HEADER = '<!-- GENERATED by afk-runner from JSON sidecars - regenerated wholesale per round. -->'

const DigestsSchema = z.record(z.string(), z.string())

interface RoundData {
  readonly findings: readonly Finding[]
  readonly resolutions: readonly Resolution[]
  readonly assumptions: readonly AssumptionRecord[]
}

async function readJson<T>(file: string, schema: z.ZodType<T>): Promise<T | null> {
  try {
    const raw = await readFile(file, 'utf8')
    return schema.parse(JSON.parse(raw))
  } catch {
    return null
  }
}

async function readRound(sidecarDir: string, round: number): Promise<RoundData> {
  const findingsFile = await readJson(path.join(sidecarDir, `findings-${round}.json`), FindingsSidecarSchema)
  const resolutionsFile = await readJson(path.join(sidecarDir, `resolutions-${round}.json`), ResolverOutputSchema)
  return {
    findings: findingsFile?.findings ?? [],
    resolutions: resolutionsFile?.resolutions ?? [],
    assumptions: resolutionsFile?.assumptions ?? [],
  }
}

/**
 * Every finding a round filed, across both lenses. The skeptic writes its own
 * sidecar, so a reader that only opens `findings-<n>.json` loses half an
 * L-profile round; the reviewer's entries win a duplicate id, matching the
 * merge order the loop itself uses.
 */
async function readRoundFindings(sidecarDir: string, round: number): Promise<Finding[]> {
  const [reviewer, skeptic] = await Promise.all([
    readJson(path.join(sidecarDir, `findings-${round}.json`), FindingsSidecarSchema),
    readJson(path.join(sidecarDir, `findings-skeptic-${round}.json`), FindingsSidecarSchema),
  ])
  return [...(skeptic?.findings ?? []), ...(reviewer?.findings ?? [])]
}

/**
 * A round's verbatim reviewer-quoted gaps, keyed by finding id. The gate joins
 * against this so its checkbox rows carry the evidence a human needs rather
 * than an identifier; a missing or malformed sidecar answers an empty join, and
 * the caller falls back to the id.
 */
export async function readRoundGaps(sidecarDir: string, round: number): Promise<Record<string, string>> {
  const gaps: Record<string, string> = {}
  for (const finding of await readRoundFindings(sidecarDir, round)) {
    gaps[finding.id] = finding.gap
  }
  return gaps
}

function readRounds(sidecarDir: string, rounds: number): Promise<RoundData[]> {
  const indices = Array.from({ length: rounds }, (_, i) => i + 1)
  return Promise.all(indices.map((round) => readRound(sidecarDir, round)))
}

function resolutionLine(resolution: Resolution | undefined): string {
  if (resolution === undefined) return '- **Resolution**: unresolved'
  const note = resolution.outcome ?? resolution.justification ?? ''
  return `- **Resolution**: ${resolution.resolution}${note === '' ? '' : ` — ${note}`}`
}

function renderRound(round: number, data: RoundData): string {
  const verdict = evaluateConvergence(data.resolutions)
  const resolved = data.resolutions.filter((r) => r.resolution !== 'dismissed').length
  const dismissed = data.resolutions.filter((r) => r.resolution === 'dismissed').length
  const record: DigestRecord = {
    round,
    counts: verdict.counts,
    resolved,
    dismissed,
    verdict: verdict.verdict,
  }
  const lines = [`### Round ${round}`, '', `**Verdict**: ${formatDigestBody(record)}`]
  if (data.findings.length === 0) {
    lines.push('', 'No findings recorded this round.')
    return lines.join('\n')
  }
  for (const finding of data.findings) {
    const resolution = data.resolutions.find((r) => r.id === finding.id)
    const finalClass = resolution?.class ?? finding.class
    lines.push(
      '',
      `#### ${finalClass} — ${finding.id}`,
      '',
      `> ${finding.gap}`,
      `- **Question**: ${finding.question}`,
      `- **Code evidence**: ${finding.code_evidence_attempted}`,
      resolutionLine(resolution),
    )
  }
  return lines.join('\n')
}

export async function materializeReview(changeDir: string, sidecarDir: string, rounds: number): Promise<void> {
  const allRounds = await readRounds(sidecarDir, rounds)
  const sections = allRounds.map((data, index) => renderRound(index + 1, data))
  const md = [REVIEW_HEADER, '', '## Review', '', sections.join('\n\n'), ''].join('\n')
  await writeFile(path.join(changeDir, 'review.md'), md)
}

export async function materializeAssumptions(changeDir: string, sidecarDir: string, rounds: number): Promise<void> {
  const allRounds = await readRounds(sidecarDir, rounds)
  const byId = new Map<string, AssumptionRecord>()
  for (const data of allRounds) {
    for (const assumption of data.assumptions) byId.set(assumption.id, assumption)
  }
  const ranked = [...byId.values()].sort((a, b) => b.blast_radius.localeCompare(a.blast_radius))
  const lines = [ASSUMPTIONS_HEADER, '', '## Assumptions', '']
  for (const assumption of ranked) {
    lines.push(
      `### ${assumption.id}: ${assumption.text}`,
      `- **Basis**: ${assumption.basis}`,
      `- **Confidence**: ${assumption.confidence}`,
      `- **Blast radius**: ${assumption.blast_radius}`,
      `- **Status**: ${assumption.status}`,
      '',
    )
  }
  await writeFile(path.join(changeDir, 'assumptions.md'), lines.join('\n'))
}

/** Where a round's change-folder snapshot lives. */
function roundDigestPath(sidecarDir: string, round: number): string {
  return path.join(sidecarDir, `round-hashes-${String(round)}.json`)
}

/**
 * Snapshot the agent-authored artifacts at a round's close. Comparing two of
 * these is what makes an `edited` resolution checkable rather than trusted: an
 * edit that moved no bytes leaves an identical snapshot. Uses the same file set
 * and digest function the gate already records with, so the two views of "what
 * the agents wrote" cannot drift apart.
 */
export async function recordRoundDigests(sidecarDir: string, changeDir: string, round: number): Promise<void> {
  const hashes = await recordArtifactHashes(changeDir, listAgentArtifacts(changeDir))
  await mkdir(sidecarDir, { recursive: true })
  await writeFile(roundDigestPath(sidecarDir, round), `${JSON.stringify(hashes, null, 2)}\n`)
}

/** A round's snapshot, or null when that round recorded none (round 0, or a pre-change run). */
export function readRoundDigests(sidecarDir: string, round: number): Promise<ArtifactDigests | null> {
  if (round < 1) return Promise.resolve(null)
  return readJson(roundDigestPath(sidecarDir, round), DigestsSchema)
}

export function createMaterializer(
  sidecarDir: string,
  changeDir: string,
  emit?: (event: { altitude: 'L2'; type: 'artifact'; action: 'materialized'; path: string }) => void,
  repoRoot?: string,
): (round: number) => Promise<void> {
  return async (round) => {
    await materializeReview(changeDir, sidecarDir, round)
    await materializeAssumptions(changeDir, sidecarDir, round)
    if (repoRoot !== undefined && emit !== undefined) {
      for (const file of ['review.md', 'assumptions.md']) {
        emit({
          altitude: 'L2',
          type: 'artifact',
          action: 'materialized',
          path: path.relative(repoRoot, path.join(changeDir, file)),
        })
      }
    }
  }
}
