// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

/** Capabilities that a task tracker provider may support. */
export type TaskCapability =
  | 'tasks.delete'
  | 'tasks.count'
  | 'tasks.relations'
  | 'tasks.watchers'
  | 'tasks.votes'
  | 'tasks.visibility'
  | 'tasks.commands'
  | 'projects.read'
  | 'projects.list'
  | 'projects.create'
  | 'projects.update'
  | 'projects.delete'
  | 'projects.team'
  | 'comments.read'
  | 'comments.create'
  | 'comments.update'
  | 'comments.delete'
  | 'comments.reactions'
  | 'labels.list'
  | 'labels.create'
  | 'labels.update'
  | 'labels.delete'
  | 'labels.assign'
  | 'statuses.list'
  | 'statuses.create'
  | 'statuses.update'
  | 'statuses.delete'
  | 'statuses.reorder'
  | 'attachments.list'
  | 'attachments.upload'
  | 'attachments.delete'
  | 'workItems.list'
  | 'workItems.create'
  | 'workItems.update'
  | 'workItems.delete'
  | 'agiles.list'
  | 'sprints.list'
  | 'sprints.create'
  | 'sprints.update'
  | 'sprints.assign'
  | 'activities.read'
  | 'queries.saved'
  | 'members.provision'

export type TaskProviderTrait =
  | 'workspace-scoped'
  | 'task-label-read-requires-provider-specific-api'
  | 'supports-command-language'
  | 'command-language:youtrack'
  | 'custom-fields'
