// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

import type { PullRequestPresentation } from './github-pulls.js'
import type { IssueContext } from './phase-context.js'
import type { AgentState } from './types.js'

/**
 * How the pull request presents itself, rendered from live issue state.
 *
 * One renderer with two callers: `handleDeliver` opens or refreshes the pull
 * request, and `handleReview` refreshes it again once the review loop has run.
 * That is the whole reason it is not a private function in `deliver.ts` any
 * more — a pull request refreshed after a review must present exactly what a
 * freshly opened one would, which is the property the shared
 * {@link PullRequestPresentation} type already exists to enforce between
 * `create` and `update`, now extended across the two phases that write it.
 *
 * The report arrives as **text**, rather than being found in the thread here.
 * Delivery passes what `findArtifact` returned; the review handler passes the
 * report it has just built, because `postAndAppend` runs in the orchestrator
 * *after* a handler returns — so a handler cannot read its own block back, and a
 * renderer that insisted on scanning the thread would refresh the pull request
 * with the previous phase's report every time.
 */
export const renderPresentation = (
  issue: IssueContext,
  state: AgentState,
  report: string | null,
): PullRequestPresentation => ({
  title: `${issue.title} (#${state.issueId})`,
  body: [
    `Closes #${state.issueId}`,
    '',
    'Generated by the OpenCode issue agent from the design spec and plan approved on the issue.',
    '',
    report ?? '_No implementation report was recorded._',
  ].join('\n'),
})
