// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

import { branchNameFor } from '../git.js'
import type { PullRequestRef } from '../github.js'
import type { PhaseHandler, PhaseInput, PhaseOutcome } from '../phase-context.js'
import { findAgentSection } from '../thread.js'

const REPORT_HEADING = '### Implementation report'

/**
 * Phase 4. Pushes the working branch and opens the pull request, or reuses the
 * open one when a retry re-enters this phase — a second run must not open a
 * duplicate PR for the same branch.
 */
export const handleDeliver: PhaseHandler = async (input): Promise<PhaseOutcome> => {
  const { deps, state } = input
  const branch = state.branch ?? branchNameFor(state.issueId)

  await deps.git.push(branch)

  const existing = await deps.github.findOpenPullRequest(branch)
  const pr = existing ?? (await openPullRequest(input, branch))

  deps.log.info({ issue: state.issueId, branch, pr: pr.number, reused: existing !== null }, 'Pull request ready')

  return {
    signal: 'PR_OPENED',
    comment: renderDelivery(pr, existing !== null),
    patch: { prUrl: pr.url },
  }
}

const openPullRequest = (input: PhaseInput, branch: string): Promise<PullRequestRef> => {
  const { deps, state, event } = input
  const report = findAgentSection(input.thread, deps.config.selfLogin, REPORT_HEADING)

  return deps.github.createPullRequest({
    head: branch,
    base: deps.config.baseBranch,
    title: `${event.issueTitle} (#${state.issueId})`,
    body: renderPrBody(state.issueId, report),
  })
}

const renderPrBody = (issueNumber: number, report: string | null): string =>
  [
    `Closes #${issueNumber}`,
    '',
    'Generated by the OpenCode issue agent from the design spec and execution plan approved on the issue.',
    '',
    report === null ? '_No implementation report was recorded._' : `## Implementation report\n\n${report}`,
  ].join('\n')

const renderDelivery = (pr: PullRequestRef, reused: boolean): string =>
  [
    '### Pull request ready',
    '',
    `${reused ? 'Updated existing' : 'Opened'} pull request: ${pr.url}`,
    '',
    'This issue closes automatically when the pull request merges.',
  ].join('\n')
