// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

import { findArtifact, REPORT_MARKER } from '../artifacts.js'
import { branchNameFor } from '../git.js'
import type { PullRequestPresentation, PullRequestRef } from '../github.js'
import type { PhaseHandler, PhaseInput, PhaseOutcome } from '../phase-context.js'

/**
 * Phase 4. Opens the pull request, or refreshes the open one when a retry
 * re-enters this phase.
 *
 * Purely API-side — phase 3 already pushed the branch. That split is what makes
 * this phase resumable at all: it needs nothing from a working tree, so it
 * behaves identically in the job that implemented the work and in a fresh
 * runner three retries later.
 */
export const handleDeliver: PhaseHandler = async (input): Promise<PhaseOutcome> => {
  const { deps, state } = input
  const branch = branchNameFor(state.issueId)
  // Rendered once and used by both paths, so a reused pull request presents
  // exactly what a freshly opened one would.
  const presentation = renderPresentation(input)

  const existing = await deps.github.findOpenPullRequest(branch)
  const pr =
    existing === null
      ? await openPullRequest(input, branch, presentation)
      : await refresh(input, existing, presentation)

  deps.log.info({ issue: state.issueId, branch, pr: pr.number, reused: existing !== null }, 'Pull request ready')

  return {
    signal: 'PR_OPENED',
    comment: renderDelivery(pr, existing !== null),
    patch: { prUrl: pr.url, prNumber: pr.number },
  }
}

const openPullRequest = async (
  input: PhaseInput,
  branch: string,
  presentation: PullRequestPresentation,
): Promise<PullRequestRef> =>
  input.deps.github.createPullRequest({ head: branch, base: await input.deps.baseBranch(), ...presentation })

/** Brings a reused pull request back in step with the issue as it reads now. */
const refresh = async (
  input: PhaseInput,
  pr: PullRequestRef,
  presentation: PullRequestPresentation,
): Promise<PullRequestRef> => {
  await input.deps.github.updatePullRequest(pr.number, presentation)
  return pr
}

const renderPresentation = (input: PhaseInput): PullRequestPresentation => {
  const report = findArtifact(input.thread, input.deps.config.selfLogin, REPORT_MARKER)

  return {
    title: `${input.issue.title} (#${input.state.issueId})`,
    body: [
      `Closes #${input.state.issueId}`,
      '',
      'Generated by the OpenCode issue agent from the design spec and execution plan approved on the issue.',
      '',
      report === null ? '_No implementation report was recorded._' : report.text,
    ].join('\n'),
  }
}

const renderDelivery = (pr: PullRequestRef, reused: boolean): string =>
  [
    '### Pull request ready',
    '',
    `${reused ? 'Refreshed' : 'Opened'} pull request: ${pr.url}`,
    '',
    'If its checks go red I will pick that up automatically and push a fix.',
    'This issue closes when the pull request merges.',
  ].join('\n')
