// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

import type { HttpHandler } from 'msw'

import {
  billingHandlers,
  identityMappingsHandlers,
  instancesHandlers,
  pluginConfigHandlers,
  statsHandlers,
} from './handlers.js'
import {
  adminCodingGuardrailsHandlers,
  adminInstancesHandlers,
  adminMcpCatalogHandlers,
  adminMcpPluginServersHandlers,
  adminReleaseNotesHandlers,
} from './settings-handlers-admin-2.js'
import {
  adminAdminsHandlers,
  adminByokHandlers,
  adminGroupsHandlers,
  adminModuleSectionsHandlers,
  adminPluginConfigHandlers,
  adminSystemHandlers,
  adminToolDefaultsHandlers,
} from './settings-handlers-admin.js'
import {
  codingIdentityHandlers,
  groupMembersHandlers,
  groupProviderHandlers,
  groupReleaseHandlers,
  guestModeHandlers,
} from './settings-handlers-group.js'
import {
  codingMcpHandlers,
  codingMcpInternalAvailableHandlers,
  codingMcpInternalSelectedHandlers,
  codingMcpNoCatalogHandlers,
  configHandlers,
  releaseSubscriptionHandlers,
  releaseSubscriptionMutatingHandlers,
  releaseSubscriptionMutationErrorHandlers,
} from './settings-handlers-personal-2.js'
import {
  codingCredentialsHandlers,
  identityGatedHandlers,
  identityHandlers,
  mcpHandlers,
  memoryEmptyCaptureOnHandlers,
  memoryHandlers,
  memoryProvisionalHandlers,
  pluginsHandlers,
} from './settings-handlers-personal.js'
import {
  adminUsersHandlers,
  byokHandlers,
  kaneoHandlers,
  reposHandlers,
  shellReadyHandlers,
} from './settings-handlers.js'

export const scenarios = {
  'admin-populated': [
    ...billingHandlers.populated,
    ...statsHandlers.populated,
    ...pluginConfigHandlers.populated,
    ...instancesHandlers.populated,
    ...identityMappingsHandlers.populated,
  ],
  'admin-empty': [
    ...billingHandlers.empty,
    ...statsHandlers.empty,
    ...pluginConfigHandlers.empty,
    ...instancesHandlers.empty,
    ...identityMappingsHandlers.empty,
  ],
  'admin-error': [
    ...billingHandlers.error,
    ...statsHandlers.error,
    ...pluginConfigHandlers.error,
    ...instancesHandlers.error,
    ...identityMappingsHandlers.error,
  ],
  'billing-populated': [...billingHandlers.populated],
  'billing-empty': [...billingHandlers.empty],
  'billing-error': [...billingHandlers.error],
  'billing-loading': [...billingHandlers.loading],
  'stats-populated': [...statsHandlers.populated],
  'stats-empty': [...statsHandlers.empty],
  'stats-error': [...statsHandlers.error],
  'plugin-config-populated': [...pluginConfigHandlers.populated],
  'plugin-config-empty': [...pluginConfigHandlers.empty],
  'plugin-config-error': [...pluginConfigHandlers.error],
  'instances-populated': [...instancesHandlers.populated],
  'instances-empty': [...instancesHandlers.empty],
  'instances-error': [...instancesHandlers.error],
  'settings-repos-populated': [...reposHandlers.populated],
  'settings-repos-empty': [...reposHandlers.empty],
  'settings-repos-error': [...reposHandlers.error],
  'settings-repos-loading': [...reposHandlers.loading],
  'settings-byok-secret-set': [...byokHandlers.secretSet],
  'settings-byok-missing': [...byokHandlers.missing],
  'settings-byok-disabled': [...byokHandlers.disabled],
  'settings-byok-error': [...byokHandlers.error],
  'settings-byok-loading': [...byokHandlers.loading],
  'settings-kaneo-populated': [...kaneoHandlers.populated],
  'settings-kaneo-not-provisioned': [...kaneoHandlers.notProvisioned],
  'settings-kaneo-error': [...kaneoHandlers.error],
  'settings-kaneo-loading': [...kaneoHandlers.loading],
  'settings-admin-users-populated': [...adminUsersHandlers.populated],
  'settings-admin-users-empty': [...adminUsersHandlers.empty],
  'settings-admin-users-error': [...adminUsersHandlers.error],
  'settings-admin-users-loading': [...adminUsersHandlers.loading],
  'settings-admin-byok-populated': [...adminByokHandlers.populated],
  'settings-admin-byok-empty': [...adminByokHandlers.empty],
  'settings-admin-byok-error': [...adminByokHandlers.error],
  'settings-admin-byok-loading': [...adminByokHandlers.loading],
  'settings-admin-system-populated': [...adminSystemHandlers.populated],
  'settings-admin-system-empty': [...adminSystemHandlers.empty],
  'settings-admin-system-error': [...adminSystemHandlers.error],
  'settings-admin-system-loading': [...adminSystemHandlers.loading],
  'settings-admin-groups-populated': [...adminGroupsHandlers.populated],
  'settings-admin-groups-empty': [...adminGroupsHandlers.empty],
  'settings-admin-groups-error': [...adminGroupsHandlers.error],
  'settings-admin-groups-loading': [...adminGroupsHandlers.loading],
  'settings-admin-admins-populated': [...adminAdminsHandlers.populated],
  'settings-admin-admins-empty': [...adminAdminsHandlers.empty],
  'settings-admin-admins-error': [...adminAdminsHandlers.error],
  'settings-admin-admins-loading': [...adminAdminsHandlers.loading],
  'settings-admin-plugin-config-populated': [...adminPluginConfigHandlers.populated],
  'settings-admin-plugin-config-empty': [...adminPluginConfigHandlers.empty],
  'settings-admin-plugin-config-error': [...adminPluginConfigHandlers.error],
  'settings-admin-plugin-config-loading': [...adminPluginConfigHandlers.loading],
  'settings-admin-module-sections-populated': [...adminModuleSectionsHandlers.populated],
  'settings-admin-module-sections-empty': [...adminModuleSectionsHandlers.empty],
  'settings-admin-module-sections-error': [...adminModuleSectionsHandlers.error],
  'settings-admin-module-sections-loading': [...adminModuleSectionsHandlers.loading],
  'settings-admin-tool-defaults-populated': [...adminToolDefaultsHandlers.populated],
  'settings-admin-tool-defaults-empty': [...adminToolDefaultsHandlers.empty],
  'settings-admin-tool-defaults-error': [...adminToolDefaultsHandlers.error],
  'settings-admin-tool-defaults-loading': [...adminToolDefaultsHandlers.loading],
  'settings-admin-release-notes-populated': [...adminReleaseNotesHandlers.populated],
  'settings-admin-release-notes-empty': [...adminReleaseNotesHandlers.empty],
  'settings-admin-release-notes-error': [...adminReleaseNotesHandlers.error],
  'settings-admin-release-notes-loading': [...adminReleaseNotesHandlers.loading],
  'settings-admin-coding-guardrails-populated': [...adminCodingGuardrailsHandlers.populated],
  'settings-admin-coding-guardrails-empty': [...adminCodingGuardrailsHandlers.empty],
  'settings-admin-coding-guardrails-error': [...adminCodingGuardrailsHandlers.error],
  'settings-admin-coding-guardrails-loading': [...adminCodingGuardrailsHandlers.loading],
  'settings-admin-mcp-catalog-populated': [...adminMcpCatalogHandlers.populated],
  'settings-admin-mcp-catalog-empty': [...adminMcpCatalogHandlers.empty],
  'settings-admin-mcp-catalog-error': [...adminMcpCatalogHandlers.error],
  'settings-admin-mcp-catalog-loading': [...adminMcpCatalogHandlers.loading],
  'settings-admin-mcp-plugin-servers-populated': [...adminMcpPluginServersHandlers.populated],
  'settings-admin-mcp-plugin-servers-empty': [...adminMcpPluginServersHandlers.empty],
  'settings-admin-mcp-plugin-servers-error': [...adminMcpPluginServersHandlers.error],
  'settings-admin-mcp-plugin-servers-loading': [...adminMcpPluginServersHandlers.loading],
  'settings-admin-instances-populated': [...adminInstancesHandlers.populated],
  'settings-admin-instances-empty': [...adminInstancesHandlers.empty],
  'settings-admin-instances-error': [...adminInstancesHandlers.error],
  'settings-admin-instances-loading': [...adminInstancesHandlers.loading],
  'settings-shell-ready': [...shellReadyHandlers],
  'settings-shell-admin-ready': [
    ...shellReadyHandlers,
    ...adminUsersHandlers.populated,
    ...pluginsHandlers.populated,
    ...adminByokHandlers.populated,
    ...adminSystemHandlers.populated,
    ...adminGroupsHandlers.populated,
    ...adminAdminsHandlers.populated,
    ...adminPluginConfigHandlers.populated,
    ...adminModuleSectionsHandlers.populated,
    ...adminToolDefaultsHandlers.populated,
    ...adminReleaseNotesHandlers.populated,
    ...adminCodingGuardrailsHandlers.populated,
    ...adminMcpCatalogHandlers.populated,
    ...adminMcpPluginServersHandlers.populated,
    ...adminInstancesHandlers.populated,
  ],
  'settings-shell-group-ready': [
    ...shellReadyHandlers,
    ...groupMembersHandlers.populated,
    ...groupProviderHandlers.populated,
    ...guestModeHandlers.populated,
    ...codingIdentityHandlers.populated,
    ...groupReleaseHandlers.populated,
    ...kaneoHandlers.populated,
  ],
  'settings-config-populated': [...configHandlers.populated],
  'settings-config-empty': [...configHandlers.empty],
  'settings-config-error': [...configHandlers.error],
  'settings-config-loading': [...configHandlers.loading],
  'settings-coding-credentials-populated': [...codingCredentialsHandlers.populated],
  'settings-coding-credentials-empty': [...codingCredentialsHandlers.empty],
  'settings-coding-credentials-error': [...codingCredentialsHandlers.error],
  'settings-coding-credentials-loading': [...codingCredentialsHandlers.loading],
  'settings-coding-mcp-populated': [...codingMcpHandlers.populated],
  'settings-coding-mcp-empty': [...codingMcpHandlers.empty],
  'settings-coding-mcp-no-catalog': [...codingMcpNoCatalogHandlers],
  'settings-coding-mcp-error': [...codingMcpHandlers.error],
  'settings-coding-mcp-loading': [...codingMcpHandlers.loading],
  'settings-coding-mcp-internal-available': [...codingMcpInternalAvailableHandlers],
  'settings-coding-mcp-internal-selected': [...codingMcpInternalSelectedHandlers],
  'settings-memory-populated': [...memoryHandlers.populated],
  'settings-memory-empty': [...memoryHandlers.empty],
  'settings-memory-error': [...memoryHandlers.error],
  'settings-memory-loading': [...memoryHandlers.loading],
  'settings-memory-empty-capture-on': [...memoryEmptyCaptureOnHandlers],
  'settings-memory-provisional': [...memoryProvisionalHandlers],
  'settings-mcp-populated': [...mcpHandlers.populated],
  'settings-mcp-empty': [...mcpHandlers.empty],
  'settings-mcp-error': [...mcpHandlers.error],
  'settings-mcp-loading': [...mcpHandlers.loading],
  'settings-plugins-populated': [...pluginsHandlers.populated],
  'settings-plugins-empty': [...pluginsHandlers.empty],
  'settings-plugins-error': [...pluginsHandlers.error],
  'settings-plugins-loading': [...pluginsHandlers.loading],
  'settings-identity-populated': [...identityHandlers.populated],
  'settings-identity-empty': [...identityHandlers.empty],
  'settings-identity-error': [...identityHandlers.error],
  'settings-identity-loading': [...identityHandlers.loading],
  'settings-identity-gated': [...identityGatedHandlers],
  'settings-release-populated': [...releaseSubscriptionHandlers.populated],
  'settings-release-empty': [...releaseSubscriptionHandlers.empty],
  'settings-release-error': [...releaseSubscriptionHandlers.error],
  'settings-release-loading': [...releaseSubscriptionHandlers.loading],
  'settings-release-mutating': [...releaseSubscriptionMutatingHandlers],
  'settings-release-mutation-error': [...releaseSubscriptionMutationErrorHandlers],
  'settings-members-populated': [...groupMembersHandlers.populated],
  'settings-members-empty': [...groupMembersHandlers.empty],
  'settings-members-error': [...groupMembersHandlers.error],
  'settings-members-loading': [...groupMembersHandlers.loading],
  'settings-guest-mode-populated': [...guestModeHandlers.populated],
  'settings-guest-mode-empty': [...guestModeHandlers.empty],
  'settings-guest-mode-error': [...guestModeHandlers.error],
  'settings-guest-mode-loading': [...guestModeHandlers.loading],
  'settings-group-provider-populated': [...groupProviderHandlers.populated],
  'settings-group-provider-empty': [...groupProviderHandlers.empty],
  'settings-group-provider-error': [...groupProviderHandlers.error],
  'settings-group-provider-loading': [...groupProviderHandlers.loading],
  'settings-coding-identity-populated': [...codingIdentityHandlers.populated],
  'settings-coding-identity-empty': [...codingIdentityHandlers.empty],
  'settings-coding-identity-error': [...codingIdentityHandlers.error],
  'settings-coding-identity-loading': [...codingIdentityHandlers.loading],
} satisfies Record<string, readonly HttpHandler[]>

export type ScenarioName = keyof typeof scenarios
