// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

import type { HttpHandler } from 'msw'

import {
  billingHandlers,
  identityMappingsHandlers,
  instancesHandlers,
  pluginConfigHandlers,
  statsHandlers,
} from './handlers.js'
import {
  adminCodingGuardrailsHandlers,
  adminInstancesHandlers,
  adminMcpCatalogHandlers,
  adminMcpPluginServersHandlers,
  adminReleaseNotesHandlers,
} from './settings-handlers-admin-2.js'
import {
  adminAnalyticsFailedSinkHandlers,
  adminAnalyticsGovernedLocalPilotHandlers,
  adminAnalyticsHandlers,
  adminAnalyticsIncompleteGovernanceHandlers,
  adminAnalyticsKillSwitchHandlers,
  adminAnalyticsReconciledHealthyHandlers,
} from './settings-handlers-admin-3.js'
import {
  adminAdminsHandlers,
  adminByokHandlers,
  adminGroupsHandlers,
  adminLlmRolesHandlers,
  adminPluginConfigHandlers,
  adminProvidersHandlers,
  adminToolDefaultsHandlers,
} from './settings-handlers-admin.js'
import { pluginsHandlers } from './settings-handlers-personal.js'
import { adminUsersHandlers, shellReadyHandlers } from './settings-handlers.js'

// Admin-area scenarios, split out of scenarios.ts to keep that file under the max-lines limit.
// Registered names and scenario ids stay byte-identical -- scenarios.ts spreads this map into
// its own registry.
export const adminScenarios = {
  'admin-populated': [
    ...billingHandlers.populated,
    ...statsHandlers.populated,
    ...pluginConfigHandlers.populated,
    ...instancesHandlers.populated,
    ...identityMappingsHandlers.populated,
  ],
  'admin-empty': [
    ...billingHandlers.empty,
    ...statsHandlers.empty,
    ...pluginConfigHandlers.empty,
    ...instancesHandlers.empty,
    ...identityMappingsHandlers.empty,
  ],
  'admin-error': [
    ...billingHandlers.error,
    ...statsHandlers.error,
    ...pluginConfigHandlers.error,
    ...instancesHandlers.error,
    ...identityMappingsHandlers.error,
  ],
  'billing-populated': [...billingHandlers.populated],
  'billing-empty': [...billingHandlers.empty],
  'billing-error': [...billingHandlers.error],
  'billing-loading': [...billingHandlers.loading],
  'stats-populated': [...statsHandlers.populated],
  'stats-empty': [...statsHandlers.empty],
  'stats-error': [...statsHandlers.error],
  'plugin-config-populated': [...pluginConfigHandlers.populated],
  'plugin-config-empty': [...pluginConfigHandlers.empty],
  'plugin-config-error': [...pluginConfigHandlers.error],
  'instances-populated': [...instancesHandlers.populated],
  'instances-empty': [...instancesHandlers.empty],
  'instances-error': [...instancesHandlers.error],
  'settings-admin-users-populated': [...adminUsersHandlers.populated],
  'settings-admin-users-empty': [...adminUsersHandlers.empty],
  'settings-admin-users-error': [...adminUsersHandlers.error],
  'settings-admin-users-loading': [...adminUsersHandlers.loading],
  'settings-admin-users-open-access-error': [...adminUsersHandlers.openAccessError],
  'settings-admin-byok-populated': [...adminByokHandlers.populated],
  'settings-admin-byok-empty': [...adminByokHandlers.empty],
  'settings-admin-byok-error': [...adminByokHandlers.error],
  'settings-admin-byok-loading': [...adminByokHandlers.loading],
  'settings-admin-providers-populated': [...adminProvidersHandlers.populated],
  'settings-admin-providers-empty': [...adminProvidersHandlers.empty],
  'settings-admin-providers-error': [...adminProvidersHandlers.error],
  'settings-admin-providers-loading': [...adminProvidersHandlers.loading],
  'settings-admin-llm-roles-populated': [...adminLlmRolesHandlers.populated, ...adminProvidersHandlers.populated],
  'settings-admin-llm-roles-empty': [...adminLlmRolesHandlers.empty, ...adminProvidersHandlers.empty],
  'settings-admin-llm-roles-error': [...adminLlmRolesHandlers.error, ...adminProvidersHandlers.populated],
  'settings-admin-llm-roles-loading': [...adminLlmRolesHandlers.loading, ...adminProvidersHandlers.populated],
  'settings-admin-groups-populated': [...adminGroupsHandlers.populated],
  'settings-admin-groups-empty': [...adminGroupsHandlers.empty],
  'settings-admin-groups-error': [...adminGroupsHandlers.error],
  'settings-admin-groups-loading': [...adminGroupsHandlers.loading],
  'settings-admin-admins-populated': [...adminAdminsHandlers.populated],
  'settings-admin-admins-empty': [...adminAdminsHandlers.empty],
  'settings-admin-admins-error': [...adminAdminsHandlers.error],
  'settings-admin-admins-loading': [...adminAdminsHandlers.loading],
  'settings-admin-plugin-config-populated': [...adminPluginConfigHandlers.populated],
  'settings-admin-plugin-config-empty': [...adminPluginConfigHandlers.empty],
  'settings-admin-plugin-config-error': [...adminPluginConfigHandlers.error],
  'settings-admin-plugin-config-loading': [...adminPluginConfigHandlers.loading],
  'settings-admin-tool-defaults-populated': [...adminToolDefaultsHandlers.populated],
  'settings-admin-tool-defaults-empty': [...adminToolDefaultsHandlers.empty],
  'settings-admin-tool-defaults-error': [...adminToolDefaultsHandlers.error],
  'settings-admin-tool-defaults-loading': [...adminToolDefaultsHandlers.loading],
  'settings-admin-release-notes-populated': [...adminReleaseNotesHandlers.populated],
  'settings-admin-release-notes-empty': [...adminReleaseNotesHandlers.empty],
  'settings-admin-release-notes-error': [...adminReleaseNotesHandlers.error],
  'settings-admin-release-notes-loading': [...adminReleaseNotesHandlers.loading],
  'settings-admin-coding-guardrails-populated': [...adminCodingGuardrailsHandlers.populated],
  'settings-admin-coding-guardrails-empty': [...adminCodingGuardrailsHandlers.empty],
  'settings-admin-coding-guardrails-error': [...adminCodingGuardrailsHandlers.error],
  'settings-admin-coding-guardrails-loading': [...adminCodingGuardrailsHandlers.loading],
  'settings-admin-mcp-catalog-populated': [...adminMcpCatalogHandlers.populated],
  'settings-admin-mcp-catalog-empty': [...adminMcpCatalogHandlers.empty],
  'settings-admin-mcp-catalog-error': [...adminMcpCatalogHandlers.error],
  'settings-admin-mcp-catalog-loading': [...adminMcpCatalogHandlers.loading],
  'settings-admin-mcp-plugin-servers-populated': [...adminMcpPluginServersHandlers.populated],
  'settings-admin-mcp-plugin-servers-empty': [...adminMcpPluginServersHandlers.empty],
  'settings-admin-mcp-plugin-servers-error': [...adminMcpPluginServersHandlers.error],
  'settings-admin-mcp-plugin-servers-loading': [...adminMcpPluginServersHandlers.loading],
  'settings-admin-instances-populated': [...adminInstancesHandlers.populated],
  'settings-admin-instances-empty': [...adminInstancesHandlers.empty],
  'settings-admin-instances-error': [...adminInstancesHandlers.error],
  'settings-admin-instances-loading': [...adminInstancesHandlers.loading],
  'settings-shell-admin-ready': [
    ...shellReadyHandlers,
    ...adminUsersHandlers.populated,
    ...pluginsHandlers.populated,
    ...adminByokHandlers.populated,
    ...adminProvidersHandlers.populated,
    ...adminLlmRolesHandlers.populated,
    ...adminGroupsHandlers.populated,
    ...adminAdminsHandlers.populated,
    ...adminPluginConfigHandlers.populated,
    ...adminToolDefaultsHandlers.populated,
    ...adminReleaseNotesHandlers.populated,
    ...adminCodingGuardrailsHandlers.populated,
    ...adminMcpCatalogHandlers.populated,
    ...adminMcpPluginServersHandlers.populated,
    ...adminInstancesHandlers.populated,
  ],
  'settings-admin-analytics-populated': [...adminAnalyticsHandlers.populated],
  'settings-admin-analytics-empty': [...adminAnalyticsHandlers.empty],
  'settings-admin-analytics-error': [...adminAnalyticsHandlers.error],
  'settings-admin-analytics-loading': [...adminAnalyticsHandlers.loading],
  'settings-admin-analytics-incomplete-governance': [...adminAnalyticsIncompleteGovernanceHandlers],
  'settings-admin-analytics-governed-local-pilot': [...adminAnalyticsGovernedLocalPilotHandlers],
  'settings-admin-analytics-kill-switch': [...adminAnalyticsKillSwitchHandlers],
  'settings-admin-analytics-failed-sink': [...adminAnalyticsFailedSinkHandlers],
  'settings-admin-analytics-reconciled-healthy': [...adminAnalyticsReconciledHealthyHandlers],
} satisfies Record<string, readonly HttpHandler[]>
