// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

import type { HttpHandler } from 'msw'

import { adminScenarios } from './scenarios-admin.js'
import {
  codingCredentialsHandlers,
  codingCredentialsOpenAiCompatibleHandlers,
  forgeHandlers,
  forgeIncompleteHandlers,
  forgeSaveErrorHandlers,
  forgeSelfHostedHandlers,
} from './settings-handlers-coding.js'
import {
  codingIdentityHandlers,
  groupMembersHandlers,
  groupProviderHandlers,
  groupProviderNamelessBoundHandlers,
  groupProviderUnassignedHandlers,
  groupReleaseHandlers,
  guestModeHandlers,
} from './settings-handlers-group.js'
import {
  analyticsLegitimateInterestHandlers,
  analyticsPreferencesHandlers,
  analyticsRightsUnavailableHandlers,
  analyticsWithdrawalInProgressHandlers,
  codingMcpHandlers,
  codingMcpInternalAvailableHandlers,
  codingMcpInternalSelectedHandlers,
  codingMcpNoCatalogHandlers,
  configHandlers,
  releaseSubscriptionHandlers,
  releaseSubscriptionMutatingHandlers,
  releaseSubscriptionMutationErrorHandlers,
} from './settings-handlers-personal-2.js'
import {
  identityGatedHandlers,
  identityHandlers,
  mcpHandlers,
  memoryEmptyCaptureOnHandlers,
  memoryHandlers,
  memoryProvisionalHandlers,
  pluginsHandlers,
} from './settings-handlers-personal.js'
import { pluginsConfigurableHandlers, pluginsIneligibleHandlers } from './settings-handlers-plugins.js'
import { taskProviderBoundHandlers } from './settings-handlers-task-provider.js'
import { byokHandlers, kaneoHandlers, reposHandlers, shellReadyHandlers } from './settings-handlers.js'

export const scenarios = {
  ...adminScenarios,
  'settings-repos-populated': [...reposHandlers.populated],
  'settings-repos-empty': [...reposHandlers.empty],
  'settings-repos-error': [...reposHandlers.error],
  'settings-repos-loading': [...reposHandlers.loading],
  'settings-byok-secret-set': [...byokHandlers.secretSet],
  'settings-byok-missing': [...byokHandlers.missing],
  'settings-byok-disabled': [...byokHandlers.disabled],
  'settings-byok-error': [...byokHandlers.error],
  'settings-byok-loading': [...byokHandlers.loading],
  'settings-kaneo-populated': [...kaneoHandlers.populated],
  'settings-kaneo-not-provisioned': [...kaneoHandlers.notProvisioned],
  'settings-kaneo-error': [...kaneoHandlers.error],
  'settings-kaneo-loading': [...kaneoHandlers.loading],
  'settings-task-provider-bound': [...taskProviderBoundHandlers],
  'settings-shell-ready': [...shellReadyHandlers],
  'settings-shell-group-ready': [
    ...shellReadyHandlers,
    ...groupMembersHandlers.populated,
    ...groupProviderHandlers.populated,
    ...guestModeHandlers.populated,
    ...codingIdentityHandlers.populated,
    ...groupReleaseHandlers.populated,
    ...kaneoHandlers.populated,
  ],
  'settings-config-populated': [...configHandlers.populated],
  'settings-config-empty': [...configHandlers.empty],
  'settings-config-error': [...configHandlers.error],
  'settings-config-loading': [...configHandlers.loading],
  'settings-coding-credentials-populated': [...codingCredentialsHandlers.populated],
  'settings-coding-credentials-empty': [...codingCredentialsHandlers.empty],
  'settings-coding-credentials-error': [...codingCredentialsHandlers.error],
  'settings-coding-credentials-loading': [...codingCredentialsHandlers.loading],
  'settings-coding-credentials-openai-compatible': [...codingCredentialsOpenAiCompatibleHandlers],
  'settings-code-host-populated': [...forgeHandlers.populated],
  'settings-code-host-empty': [...forgeHandlers.empty],
  'settings-code-host-error': [...forgeHandlers.error],
  'settings-code-host-loading': [...forgeHandlers.loading],
  'settings-code-host-save-error': [...forgeSaveErrorHandlers],
  'settings-code-host-incomplete': [...forgeIncompleteHandlers],
  'settings-code-host-self-hosted': [...forgeSelfHostedHandlers],
  'settings-coding-mcp-populated': [...codingMcpHandlers.populated],
  'settings-coding-mcp-empty': [...codingMcpHandlers.empty],
  'settings-coding-mcp-no-catalog': [...codingMcpNoCatalogHandlers],
  'settings-coding-mcp-error': [...codingMcpHandlers.error],
  'settings-coding-mcp-loading': [...codingMcpHandlers.loading],
  'settings-coding-mcp-internal-available': [...codingMcpInternalAvailableHandlers],
  'settings-coding-mcp-internal-selected': [...codingMcpInternalSelectedHandlers],
  'settings-memory-populated': [...memoryHandlers.populated],
  'settings-memory-empty': [...memoryHandlers.empty],
  'settings-memory-error': [...memoryHandlers.error],
  'settings-memory-loading': [...memoryHandlers.loading],
  'settings-memory-empty-capture-on': [...memoryEmptyCaptureOnHandlers],
  'settings-memory-provisional': [...memoryProvisionalHandlers],
  'settings-mcp-populated': [...mcpHandlers.populated],
  'settings-mcp-empty': [...mcpHandlers.empty],
  'settings-mcp-error': [...mcpHandlers.error],
  'settings-mcp-loading': [...mcpHandlers.loading],
  'settings-plugins-populated': [...pluginsHandlers.populated],
  'settings-plugins-empty': [...pluginsHandlers.empty],
  'settings-plugins-error': [...pluginsHandlers.error],
  'settings-plugins-loading': [...pluginsHandlers.loading],
  'settings-plugins-configurable': [...pluginsConfigurableHandlers],
  'settings-plugins-ineligible': [...pluginsIneligibleHandlers],
  'settings-identity-populated': [...identityHandlers.populated],
  'settings-identity-empty': [...identityHandlers.empty],
  'settings-identity-error': [...identityHandlers.error],
  'settings-identity-loading': [...identityHandlers.loading],
  'settings-identity-gated': [...identityGatedHandlers],
  'settings-release-populated': [...releaseSubscriptionHandlers.populated],
  'settings-release-empty': [...releaseSubscriptionHandlers.empty],
  'settings-release-error': [...releaseSubscriptionHandlers.error],
  'settings-release-loading': [...releaseSubscriptionHandlers.loading],
  'settings-release-mutating': [...releaseSubscriptionMutatingHandlers],
  'settings-release-mutation-error': [...releaseSubscriptionMutationErrorHandlers],
  'settings-members-populated': [...groupMembersHandlers.populated],
  'settings-members-empty': [...groupMembersHandlers.empty],
  'settings-members-error': [...groupMembersHandlers.error],
  'settings-members-loading': [...groupMembersHandlers.loading],
  'settings-guest-mode-populated': [...guestModeHandlers.populated],
  'settings-guest-mode-empty': [...guestModeHandlers.empty],
  'settings-guest-mode-error': [...guestModeHandlers.error],
  'settings-guest-mode-loading': [...guestModeHandlers.loading],
  'settings-group-provider-populated': [...groupProviderHandlers.populated],
  'settings-group-provider-empty': [...groupProviderHandlers.empty],
  'settings-group-provider-error': [...groupProviderHandlers.error],
  'settings-group-provider-loading': [...groupProviderHandlers.loading],
  'settings-group-provider-unassigned': [...groupProviderUnassignedHandlers],
  'settings-group-provider-nameless-bound': [...groupProviderNamelessBoundHandlers],
  'settings-coding-identity-populated': [...codingIdentityHandlers.populated],
  'settings-coding-identity-empty': [...codingIdentityHandlers.empty],
  'settings-coding-identity-error': [...codingIdentityHandlers.error],
  'settings-coding-identity-loading': [...codingIdentityHandlers.loading],
  'settings-analytics-populated': [...analyticsPreferencesHandlers.populated],
  'settings-analytics-empty': [...analyticsPreferencesHandlers.empty],
  'settings-analytics-error': [...analyticsPreferencesHandlers.error],
  'settings-analytics-loading': [...analyticsPreferencesHandlers.loading],
  'settings-analytics-withdrawal-in-progress': [...analyticsWithdrawalInProgressHandlers],
  'settings-analytics-rights-unavailable': [...analyticsRightsUnavailableHandlers],
  'settings-analytics-legitimate-interest-unset': [...analyticsLegitimateInterestHandlers],
} satisfies Record<string, readonly HttpHandler[]>

export type ScenarioName = keyof typeof scenarios
