// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { z } from 'zod'

import type { AssumptionRecord, Finding, Resolution } from './agent-layer.js'
import { FindingsSidecarSchema } from './agent-layer.js'
import { formatDigestBody } from './renderer.js'
import type { DigestRecord } from './replay.js'
import { ResolverOutputSchema } from './review-loop.js'
import { evaluateConvergence } from './review-model.js'

const REVIEW_HEADER =
  '<!-- GENERATED by sdd-runner from findings/resolutions sidecars - regenerated wholesale per round. -->'
const ASSUMPTIONS_HEADER = '<!-- GENERATED by sdd-runner from JSON sidecars - regenerated wholesale per round. -->'

interface RoundData {
  readonly findings: readonly Finding[]
  readonly resolutions: readonly Resolution[]
  readonly assumptions: readonly AssumptionRecord[]
}

async function readJson<T>(file: string, schema: z.ZodType<T>): Promise<T | null> {
  try {
    const raw = await readFile(file, 'utf8')
    return schema.parse(JSON.parse(raw))
  } catch {
    return null
  }
}

async function readRound(sidecarDir: string, round: number): Promise<RoundData> {
  const findingsFile = await readJson(path.join(sidecarDir, `findings-${round}.json`), FindingsSidecarSchema)
  const resolutionsFile = await readJson(path.join(sidecarDir, `resolutions-${round}.json`), ResolverOutputSchema)
  return {
    findings: findingsFile?.findings ?? [],
    resolutions: resolutionsFile?.resolutions ?? [],
    assumptions: resolutionsFile?.assumptions ?? [],
  }
}

function readRounds(sidecarDir: string, rounds: number): Promise<RoundData[]> {
  const indices = Array.from({ length: rounds }, (_, i) => i + 1)
  return Promise.all(indices.map((round) => readRound(sidecarDir, round)))
}

function resolutionLine(resolution: Resolution | undefined): string {
  if (resolution === undefined) return '- **Resolution**: unresolved'
  const note = resolution.outcome ?? resolution.justification ?? ''
  return `- **Resolution**: ${resolution.resolution}${note === '' ? '' : ` — ${note}`}`
}

function renderRound(round: number, data: RoundData): string {
  const verdict = evaluateConvergence(data.resolutions)
  const resolved = data.resolutions.filter((r) => r.resolution !== 'dismissed').length
  const dismissed = data.resolutions.filter((r) => r.resolution === 'dismissed').length
  const record: DigestRecord = {
    round,
    counts: verdict.counts,
    resolved,
    dismissed,
    verdict: verdict.verdict,
  }
  const lines = [`### Round ${round}`, '', `**Verdict**: ${formatDigestBody(record)}`]
  if (data.findings.length === 0) {
    lines.push('', 'No findings recorded this round.')
    return lines.join('\n')
  }
  for (const finding of data.findings) {
    const resolution = data.resolutions.find((r) => r.id === finding.id)
    const finalClass = resolution?.class ?? finding.class
    lines.push(
      '',
      `#### ${finalClass} — ${finding.id}`,
      '',
      `> ${finding.gap}`,
      `- **Question**: ${finding.question}`,
      `- **Code evidence**: ${finding.code_evidence_attempted}`,
      resolutionLine(resolution),
    )
  }
  return lines.join('\n')
}

export interface ArtifactFile {
  readonly path: string
  readonly content: string
}

interface TermRender {
  readonly file: string
  readonly value: string
  readonly quote: string
}

const STRATEGY_WORD = /(drizzle|prisma|knex|hand-written|handwritten|hand-rolled)/iu
const INTERVAL_LITERAL = /(\d+)\s*\*\s*60\s*\*\s*1000/gu
const BACKTICKED_IDENTIFIER = /`([^`\s]+)`/gu
const IDENTIFIER_SHAPE = /^[a-z][A-Za-z0-9]*(?:_[A-Za-z0-9]+)*$/u

function normalizeStrategy(word: string): string {
  const lower = word.toLowerCase()
  return lower === 'handwritten' || lower === 'hand-rolled' ? 'hand-written' : lower
}

function firstQuotePerValue(renders: readonly TermRender[]): Map<string, TermRender> {
  const byValue = new Map<string, TermRender>()
  for (const render of renders) if (!byValue.has(render.value)) byValue.set(render.value, render)
  return byValue
}

function disagreement(
  kind: string,
  renders: readonly TermRender[],
): { readonly kind: string; readonly renders: readonly TermRender[] } | null {
  const crossFile = new Set(renders.map((render) => render.file)).size >= 2
  const distinct = firstQuotePerValue(renders)
  if (!crossFile || distinct.size < 2) return null
  return { kind, renders: [...distinct.values()] }
}

function renderLines(entries: readonly TermRender[]): string {
  return entries.map((render) => `${render.file}: '${render.quote}'`).join(' vs ')
}

function strategyRenders(files: readonly ArtifactFile[]): TermRender[] {
  const renders: TermRender[] = []
  for (const file of files) {
    for (const line of file.content.split('\n')) {
      if (!/\bmigrations?\b/iu.test(line)) continue
      const match = STRATEGY_WORD.exec(line)
      if (match === null) continue
      renders.push({ file: file.path, value: normalizeStrategy(match[0]), quote: line.trim() })
    }
  }
  return renders
}

function intervalRenders(files: readonly ArtifactFile[]): TermRender[] {
  const renders: TermRender[] = []
  for (const file of files) {
    for (const line of file.content.split('\n')) {
      for (const match of line.matchAll(INTERVAL_LITERAL)) {
        renders.push({ file: file.path, value: match[0].replace(/\s+/gu, ''), quote: line.trim() })
      }
    }
  }
  return renders
}

function tableNameRenders(files: readonly ArtifactFile[]): TermRender[] {
  const perFile = new Map<string, Map<string, TermRender>>()
  for (const file of files) {
    const seen = perFile.get(file.path) ?? new Map<string, TermRender>()
    for (const match of file.content.matchAll(BACKTICKED_IDENTIFIER)) {
      const token = match[1]!
      if (!IDENTIFIER_SHAPE.test(token)) continue
      if (!seen.has(token)) seen.set(token, { file: file.path, value: token, quote: token })
    }
    perFile.set(file.path, seen)
  }
  const byNormalized = new Map<string, TermRender[]>()
  for (const seen of perFile.values()) {
    for (const render of seen.values()) {
      const key = render.value.toLowerCase().replaceAll('_', '')
      const bucket = byNormalized.get(key) ?? []
      bucket.push(render)
      byNormalized.set(key, bucket)
    }
  }
  const renders: TermRender[] = []
  for (const bucket of byNormalized.values()) {
    const filesHaving = new Set(bucket.map((render) => render.file))
    if (filesHaving.size >= 2 && new Set(bucket.map((render) => render.value)).size >= 2) {
      renders.push(...bucket)
    }
  }
  return renders
}

/**
 * Deterministic cross-artifact consistency scan (loop-memory D6): seeded
 * decision-term vocabulary (migration strategy, interval literals, backticked
 * table/column identifiers) whose renderings disagree across artifacts become
 * synthesized MATERIAL findings naming both files and both renderings — no
 * spawn, no tokens. Generality is deliberately seeded; widening is
 * analyzer-driven.
 */
export function consistencyFindings(files: readonly ArtifactFile[]): Finding[] {
  const disagreements = [
    disagreement('migration strategy', strategyRenders(files)),
    disagreement('recompute interval', intervalRenders(files)),
    disagreement('table/column naming', tableNameRenders(files)),
  ].filter((entry): entry is { kind: string; renders: readonly TermRender[] } => entry !== null)
  return disagreements.map((entry, index) => ({
    id: `C${index + 1}`,
    class: 'MATERIAL',
    gap: `Consistency: ${entry.kind} rendered differently across artifacts — ${renderLines(entry.renders)}`,
    question: `Which rendering of the ${entry.kind} is authoritative?`,
    code_evidence_attempted: `seeded consistency scan over ${files.map((file) => file.path).join(', ')}`,
  }))
}

export async function materializeReview(changeDir: string, sidecarDir: string, rounds: number): Promise<void> {
  const allRounds = await readRounds(sidecarDir, rounds)
  const sections = allRounds.map((data, index) => renderRound(index + 1, data))
  const md = [REVIEW_HEADER, '', '## Review', '', sections.join('\n\n'), ''].join('\n')
  await writeFile(path.join(changeDir, 'review.md'), md)
}

export async function materializeAssumptions(changeDir: string, sidecarDir: string, rounds: number): Promise<void> {
  const allRounds = await readRounds(sidecarDir, rounds)
  const byId = new Map<string, AssumptionRecord>()
  for (const data of allRounds) {
    for (const assumption of data.assumptions) byId.set(assumption.id, assumption)
  }
  const ranked = [...byId.values()].sort((a, b) => b.blast_radius.localeCompare(a.blast_radius))
  const lines = [ASSUMPTIONS_HEADER, '', '## Assumptions', '']
  for (const assumption of ranked) {
    lines.push(
      `### ${assumption.id}: ${assumption.text}`,
      `- **Basis**: ${assumption.basis}`,
      `- **Confidence**: ${assumption.confidence}`,
      `- **Blast radius**: ${assumption.blast_radius}`,
      `- **Status**: ${assumption.status}`,
      '',
    )
  }
  await writeFile(path.join(changeDir, 'assumptions.md'), lines.join('\n'))
}

export function createMaterializer(
  sidecarDir: string,
  changeDir: string,
  emit?: (event: { altitude: 'L2'; type: 'artifact'; action: 'materialized'; path: string }) => void,
  repoRoot?: string,
): (round: number) => Promise<void> {
  return async (round) => {
    await materializeReview(changeDir, sidecarDir, round)
    await materializeAssumptions(changeDir, sidecarDir, round)
    if (repoRoot !== undefined && emit !== undefined) {
      for (const file of ['review.md', 'assumptions.md']) {
        emit({
          altitude: 'L2',
          type: 'artifact',
          action: 'materialized',
          path: path.relative(repoRoot, path.join(changeDir, file)),
        })
      }
    }
  }
}
