// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Dmitriy Lazarev
// Use of this software is governed by the Business Source License 1.1.
// See LICENSE in the project root for details.

import { createHash } from 'node:crypto'
import { mkdir, readdir, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { z } from 'zod'

import { slugify } from './config.js'

export const PlanChildSchema = z.object({
  id: z.string().min(1),
  instruction: z.string().min(1),
  deps: z.array(z.string().min(1)).default([]),
  capabilities: z.array(z.string().min(1)).optional(),
  /** D6: the existing change folder this child adopts (a decompose-split continuation); absent on ordinary children. */
  changeName: z.string().min(1).optional(),
})
export type PlanChild = z.infer<typeof PlanChildSchema>

export const PlanSchema = z.object({
  children: z.array(PlanChildSchema).min(1),
})
export type Plan = z.infer<typeof PlanSchema>

function joinIds(ids: Iterable<string>): string {
  return [...ids].join(', ')
}

export function validatePlan(input: unknown): Plan {
  const plan = PlanSchema.parse(input)
  const problems: string[] = []

  const seen = new Set<string>()
  const duplicates = new Set<string>()
  for (const child of plan.children) {
    if (seen.has(child.id)) duplicates.add(child.id)
    seen.add(child.id)
  }
  if (duplicates.size > 0) problems.push(`duplicate child ids: ${joinIds(duplicates)}`)

  const unknownDeps = new Set<string>()
  const selfDeps = new Set<string>()
  for (const child of plan.children) {
    for (const dep of child.deps) {
      if (dep === child.id) selfDeps.add(child.id)
      else if (!seen.has(dep)) unknownDeps.add(dep)
    }
  }
  if (unknownDeps.size > 0) problems.push(`unknown deps: ${joinIds(unknownDeps)}`)
  if (selfDeps.size > 0) problems.push(`self-dependencies: ${joinIds(selfDeps)}`)

  if (problems.length > 0) throw new Error(`invalid plan: ${problems.join('; ')}`)
  return plan
}

export function topoSortChildren(input: unknown): PlanChild[] {
  const plan = validatePlan(input)
  const done = new Set<string>()
  const remaining = [...plan.children]
  const sorted: PlanChild[] = []
  while (remaining.length > 0) {
    const next = remaining.find((candidate) => candidate.deps.every((dep) => done.has(dep)))
    if (next === undefined) {
      throw new Error(`dependency cycle among: ${remaining.map((child) => child.id).join(', ')}`)
    }
    done.add(next.id)
    sorted.push(next)
    remaining.splice(remaining.indexOf(next), 1)
  }
  return sorted
}

/**
 * D4: sha-256 over `JSON.stringify(topo-ordered [id, instruction] pairs)`,
 * sliced to a 16-hex prefix. Order-sensitive by design; instructions are
 * hashed so an instruction-only replan digests differently — the
 * interrupted-replan recovery compares this against `state.plan.digest`.
 */
export function planDigest(children: readonly PlanChild[]): string {
  return createHash('sha256')
    .update(JSON.stringify(children.map((child) => [child.id, child.instruction])))
    .digest('hex')
    .slice(0, 16)
}

/** Injected fs seam so plan materialization stays hermetic under test (D5). */
export interface PlanFsDeps {
  readonly mkdir: (dir: string, options: { recursive: boolean }) => Promise<string | undefined>
  readonly writeFile: (file: string, data: string) => Promise<void>
  readonly readdir: (dir: string) => Promise<string[]>
  readonly unlink: (file: string) => Promise<void>
}

const CHILDREN_DIR = 'children'
const CHILD_MARKER = '<!-- GENERATED by sdd-runner from the run plan - regenerated wholesale per replan. -->'

function renderChild(child: PlanChild): string {
  const lines: string[] = [CHILD_MARKER, '', `# ${child.id}`, '', child.instruction]
  if (child.deps.length > 0) lines.push('', `deps: ${child.deps.join(', ')}`)
  const capabilities = child.capabilities ?? []
  if (capabilities.length > 0) lines.push('', `capabilities: ${capabilities.join(', ')}`)
  return `${lines.join('\n')}\n`
}

/** One task file per child at `<runDir>/children/<n>-<slug>.md`, numbered in topo order. */
export async function materializeChildFiles(
  input: unknown,
  runDir: string,
  deps: PlanFsDeps = { mkdir, writeFile, readdir, unlink },
): Promise<string[]> {
  const children = topoSortChildren(input)
  const childrenDir = path.join(runDir, CHILDREN_DIR)
  await deps.mkdir(childrenDir, { recursive: true })
  const entries = children.map((child, index) => ({
    name: `${index + 1}-${slugify(child.id)}.md`,
    content: renderChild(child),
  }))
  const wanted = new Set(entries.map((entry) => entry.name))
  const stale = (await deps.readdir(childrenDir)).filter((name) => name.endsWith('.md') && !wanted.has(name))
  await Promise.all(stale.map((name) => deps.unlink(path.join(childrenDir, name))))
  await Promise.all(entries.map((entry) => deps.writeFile(path.join(childrenDir, entry.name), entry.content)))
  return entries.map((entry) => path.join(CHILDREN_DIR, entry.name))
}
